import {
  buildSchoolOverviewRows,
  buildSevenDayTrendData,
  calculateMonthlyPaymentAmount,
} from "./dashboard-helpers";
import type {
  HomeworkRecordItem,
  MealRecordItem,
  PaymentRecordItem,
  StudentItem,
} from "@/lib/server-data";

const today = "2026-04-02";

const students: StudentItem[] = [
  {
    id: "stu-1",
    name: "张三",
    schoolId: "school-a",
    schoolName: "朝阳校区",
    classId: "class-a",
    className: "一班",
    grade: "一年级",
    gradeId: "grade-1",
    guardianId: "guardian-1",
    guardianName: "家长A",
    guardianPhone: "13800000001",
    status: "active",
  },
  {
    id: "stu-2",
    name: "李四",
    schoolId: "school-b",
    schoolName: "海淀校区",
    classId: "class-b",
    className: "二班",
    grade: "二年级",
    gradeId: "grade-2",
    guardianId: "guardian-2",
    guardianName: "家长B",
    guardianPhone: "13800000002",
    status: "active",
  },
  {
    id: "stu-3",
    name: "王五",
    schoolId: "school-a",
    schoolName: "朝阳校区",
    classId: "class-c",
    className: "三班",
    grade: "三年级",
    gradeId: "grade-3",
    guardianId: "guardian-3",
    guardianName: "家长C",
    guardianPhone: "13800000003",
    status: "active",
  },
];

const mealRecords: MealRecordItem[] = [
  {
    id: "meal-1",
    studentId: "stu-1",
    studentName: "张三",
    serviceDate: "2026-04-02",
    status: "completed",
    imageUrls: [],
    recordedBy: "老师甲",
    recordedById: "teacher-1",
    remark: "",
  },
  {
    id: "meal-2",
    studentId: "stu-1",
    studentName: "张三",
    serviceDate: "2026-03-30",
    status: "completed",
    imageUrls: [],
    recordedBy: "老师甲",
    recordedById: "teacher-1",
    remark: "",
  },
  {
    id: "meal-3",
    studentId: "stu-2",
    studentName: "李四",
    serviceDate: "2026-04-01",
    status: "completed",
    imageUrls: [],
    recordedBy: "老师乙",
    recordedById: "teacher-2",
    remark: "",
  },
  {
    id: "meal-4",
    studentId: "stu-3",
    studentName: "王五",
    serviceDate: "2026-03-20",
    status: "completed",
    imageUrls: [],
    recordedBy: "老师甲",
    recordedById: "teacher-1",
    remark: "",
  },
  {
    id: "meal-5",
    studentId: "stu-2",
    studentName: "李四",
    serviceDate: "2026-04-02",
    status: "pending",
    imageUrls: [],
    recordedBy: "老师乙",
    recordedById: "teacher-2",
    remark: "",
  },
];

const homeworkRecords: HomeworkRecordItem[] = [
  {
    id: "homework-1",
    assignmentId: "assignment-1",
    className: "一班",
    schoolName: "朝阳校区",
    serviceDate: "2026-04-02",
    status: "completed",
    studentId: "stu-1",
    studentName: "张三",
    subject: "数学",
    subjectSummary: "口算",
    imageUrls: [],
    recordedBy: "老师甲",
    recordedById: "teacher-1",
    remark: "",
  },
  {
    id: "homework-2",
    assignmentId: "assignment-2",
    className: "二班",
    schoolName: "海淀校区",
    serviceDate: "2026-04-01",
    status: "partial",
    studentId: "stu-2",
    studentName: "李四",
    subject: "语文",
    subjectSummary: "朗读",
    imageUrls: [],
    recordedBy: "老师乙",
    recordedById: "teacher-2",
    remark: "",
  },
  {
    id: "homework-3",
    assignmentId: "assignment-3",
    className: "三班",
    schoolName: "朝阳校区",
    serviceDate: "2026-03-29",
    status: "completed",
    studentId: "stu-3",
    studentName: "王五",
    subject: "英语",
    subjectSummary: "听写",
    imageUrls: [],
    recordedBy: "老师甲",
    recordedById: "teacher-1",
    remark: "",
  },
  {
    id: "homework-4",
    assignmentId: "assignment-4",
    className: "一班",
    schoolName: "朝阳校区",
    serviceDate: "2026-03-18",
    status: "completed",
    studentId: "stu-1",
    studentName: "张三",
    subject: "科学",
    subjectSummary: "观察",
    imageUrls: [],
    recordedBy: "老师甲",
    recordedById: "teacher-1",
    remark: "",
  },
];

const paymentRecords: PaymentRecordItem[] = [
  {
    id: "payment-1",
    paidAt: "2026-04-01T08:00:00Z",
    paymentAmount: 1200,
    paymentType: "cash",
    periodEndDate: "2026-06-30",
    periodStartDate: "2026-04-01",
    refundAmount: 0,
    refundedAt: "",
    refundRemark: "",
    remark: "",
    schoolId: "school-a",
    schoolName: "朝阳校区",
    studentId: "stu-1",
    studentName: "张三",
    guardianId: "guardian-1",
    guardianName: "家长A",
    guardianPhone: "13800000001",
    classId: "class-a",
    className: "一班",
    gradeId: "grade-1",
    gradeName: "一年级",
    status: "paid",
  },
  {
    id: "payment-2",
    paidAt: "2026-04-02T12:30:00Z",
    paymentAmount: 800,
    paymentType: "cash",
    periodEndDate: "2026-06-30",
    periodStartDate: "2026-04-01",
    refundAmount: 0,
    refundedAt: "",
    refundRemark: "",
    remark: "",
    schoolId: "school-b",
    schoolName: "海淀校区",
    studentId: "stu-2",
    studentName: "李四",
    guardianId: "guardian-2",
    guardianName: "家长B",
    guardianPhone: "13800000002",
    classId: "class-b",
    className: "二班",
    gradeId: "grade-2",
    gradeName: "二年级",
    status: "paid",
  },
  {
    id: "payment-3",
    paidAt: "2026-03-28T12:30:00Z",
    paymentAmount: 666,
    paymentType: "cash",
    periodEndDate: "2026-05-31",
    periodStartDate: "2026-03-01",
    refundAmount: 0,
    refundedAt: "",
    refundRemark: "",
    remark: "",
    schoolId: "school-a",
    schoolName: "朝阳校区",
    studentId: "stu-3",
    studentName: "王五",
    guardianId: "guardian-3",
    guardianName: "家长C",
    guardianPhone: "13800000003",
    classId: "class-c",
    className: "三班",
    gradeId: "grade-3",
    gradeName: "三年级",
    status: "paid",
  },
];

test("calculateMonthlyPaymentAmount 只统计本月 paymentAmount", () => {
  expect(calculateMonthlyPaymentAmount(paymentRecords, today)).toBe(2000);
});

test("buildSevenDayTrendData 输出最近七天并按状态聚合", () => {
  expect(buildSevenDayTrendData(mealRecords, homeworkRecords, today)).toEqual([
    { date: "2026-03-27", label: "3/27", meals: 0, homework: 0 },
    { date: "2026-03-28", label: "3/28", meals: 0, homework: 0 },
    { date: "2026-03-29", label: "3/29", meals: 0, homework: 1 },
    { date: "2026-03-30", label: "3/30", meals: 1, homework: 0 },
    { date: "2026-03-31", label: "3/31", meals: 0, homework: 0 },
    { date: "2026-04-01", label: "4/1", meals: 1, homework: 1 },
    { date: "2026-04-02", label: "4/2", meals: 1, homework: 1 },
  ]);
});

test("buildSchoolOverviewRows 按学校汇总学生数与近七天记录", () => {
  expect(buildSchoolOverviewRows(students, mealRecords, homeworkRecords, today)).toEqual([
    {
      schoolName: "朝阳校区",
      studentCount: 2,
      mealCount: 2,
      homeworkCount: 2,
    },
    {
      schoolName: "海淀校区",
      studentCount: 1,
      mealCount: 1,
      homeworkCount: 1,
    },
  ]);
});
